tv_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from show_app.views import MyAppLoginView, MyAppLogoutView, form_register_view
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('show_app.urls')),
    path('users/', include('users.urls')),
    path('accounts/login/', MyAppLoginView.as_view(), name='login'),
    path('accounts/logout/', MyAppLogoutView.as_view(), name='logout'),
    path('accounts/password_change/',PasswordChangeView.as_view(template_name='registration/change_password.html'),
    name='password_change'),
    path('accounts/password_change/done/', PasswordChangeDoneView.as_view(template_name='registration/password_changed.html'),
     name='password_change_done'),
    path('accounts/registration/', form_register_view, name='registration'),
    

]

if settings.DEBUG:
    
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import account_view, ajax_delete_show, trash_view, trash_clear

app_name = 'users'

urlpatterns = [
    path('<int:pk>/delete/', ajax_delete_show, name='delete'),
    path('<int:pk>/', account_view, name='account'),
    path('trash/<int:pk>/', trash_view, name='trash'),
    path('trash/clear/<int:pk>', trash_clear, name='trash_clear'),

]

tv_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}Hello{% endblock title %}</title>
  <meta name='description' content="{{ description_words }}" >

  <link rel='icon' href='https://sledoktv.ru/media/photo_2021-04-26_18-20-06.jpg' type='image/jpeg'>
  <meta name="google-site-verification" content="EAZANni1HU-weDnHrRX0OZaR_PcI31p7OGjvO_6aN04" />
` <meta name="yandex-verification" content="a434d47d5858a9f2"/>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="{% static 'js/nav.js' %}"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="http://ваш_сайт/css/font-awesome.min.css"> -->
  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'reset.css' %}">
  <link rel="stylesheet" href="{% static 'nav.css' %}">
  {% block link %}


  {% endblock link %}
  <!-- <link rel="stylesheet" href="{% static 'main.css' %}"> -->

  
</head>
<body>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
      (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
      m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
      (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

      ym(76681352, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true
      });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/76681352" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
      <header class="mg-header">
        <div class="head-1">
          <a href="{% url 'index' %}" class="logo-href"><div class="logo">СЛЕДОК <span class="first">T</span><span class="second">V</span> </div></a>
          <form action="" method="get" class="search">
            <input  placeholder="Сериал    Аниме " type="search" id='search' class="jsInput">
            <button type="submit" class="jsButton" id="ButtonSearch"><i class="fas fa-search fa-3x" id="icon"></i></button>
            <div class="compilation">
                

            </div>

          </form>
          

          <div>
            {% if user.is_authenticated %}
                 <p class="username"> {{ user.username }} <a href="{% url 'users:account' pk=user.pk %}"><i class="fa fa-user-circle" aria-hidden="true"></i></a></p>
                 

            {% else %}

            <a href="{% url 'login' %}" class="log auth">Вход</a>
            <a href="{% url 'registration' %}" class="reg auth ">Регистрация</a>

            {% endif %}
          </div>
          

        </div>
        <nav>
          <ul class="nav">
            <li><a href="{% url 'about' %}" class="one">О сайте</a></li>
            <li><a href="{% url 'anime' %}" class="two">Аниме</a></li>
            <li><a href="{% url 'shows' %}" class="three">Сериалы</a></li>
            <li><a href="{% url 'cartoons' %}" class="five">Мультфильмы</a></li>

            {% comment %} <li><a href="#" class="four">Календарь</a></li> {% endcomment %}  
            
          </ul>
        </nav>
          
      </header>
      <div class='header'>
      <div class='phone-header'>
            <div class='logo' >
              <a href='{% url "index" %}'><div class="logo">СЛЕДОК <span class="first">T</span><span class="second">V</span> </div></a>

            </div>
            <i class="fa fa-bars fa-1x" aria-hidden="true" id='menu-bars'></i>

      </div>
      <div id='menu-phone'>
            <a href="{% url 'about' %}" class='one-phone' >О сайте</a>
            <a href="{% url 'anime' %}" class='two-phone' >Аниме</a>
            <a href="{% url 'shows' %}" class='three-phone' >Сериалы</a>
            <a href="{% url 'cartoons' %}" class='four-phone' >Мультфильмы</a>
            {% if user.is_authenticated %}
                 <a href="{% url 'users:account' pk=user.pk %}" class='eith-phone'>{{user.username}} / Личный кабинет</i></a>
                 

            {% else %}
            <a href="{% url 'login' %}" class="six-phone">Вход</a>
            <a href="{% url 'registration' %}" class="seven-phone">Регистрация</a>
            {% endif %}


            
          



      </div>
      <div class='search-phone'>
        <div class='a'>
          <input type='search-2' placeholder="Сериал    Аниме " id='search-phone'>
          <button><i class="fas fa-search fa-2x"></i></button>
            <div class='compilation-2'>
                    
            </div>
            </div>
        </div>
      </div>
      
      {% block content %}

      <div class="main">
        <div class="board-right">   
          <h1>Самое Популярное</h1>
          <div class="tv-shows">
            
            <div class="show">
              <a href="#">
                <img src="https://static.tvmaze.com/uploads/images/medium_portrait/276/690357.jpg" class="original-image">
              </a>
              <div class="show-description">
                <a href="#">The Outpost</a>
              </div>
              <div class="like-raiting"> 
                <a href="#"><i class="fa fa-heart" aria-hidden="true"></i></a>
              </div>
              <a href="#"><div class="show-raiting" id='show-raiting'>
                <i class="fa fa-star" aria-hidden="true"></i>
                75
              </div></a>

            </div>
            
            



          </div>
        </div>
        <div class="board-left">
          <h1>Ближайшие даты</h1>
          <div class="mini-shedule"> 

          </div>
          
        </div>
        


      </div>
      {% endblock content %}
</body>
</html>