tv_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from show_app.views import MyAppLoginView, MyAppLogoutView, form_register_view
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('show_app.urls')),
    path('users/', include('users.urls')),
    path('accounts/login/', MyAppLoginView.as_view(), name='login'),
    path('accounts/logout/', MyAppLogoutView.as_view(), name='logout'),
    path('accounts/password_change/',PasswordChangeView.as_view(template_name='registration/change_password.html'),
    name='password_change'),
    path('accounts/password_change/done/', PasswordChangeDoneView.as_view(template_name='registration/password_changed.html'),
     name='password_change_done'),
    path('accounts/registration/', form_register_view, name='registration'),
    

]

if settings.DEBUG:
    
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import account_view, ajax_delete_show, trash_view, trash_clear

app_name = 'users'

urlpatterns = [
    path('<int:pk>/delete/', ajax_delete_show, name='delete'),
    path('<int:pk>/', account_view, name='account'),
    path('trash/<int:pk>/', trash_view, name='trash'),
    path('trash/clear/<int:pk>', trash_clear, name='trash_clear'),

]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect

from show_app.models import Sender
from show_app.models import Show
from show_app.tasks import send_instructions


def alert_setting(data, pk) -> User:
    user = User.objects.get(pk=pk)
    user.siteusermodel.sender = Sender.objects.get(name=data['send'])
    time_1 = data['time_1']
    time_2 = data['time_2']
    user.siteusermodel.send = True
    if time_1:
        user.siteusermodel.time_1 = True
    if time_2:
        user.siteusermodel.time_2 = True
    user.siteusermodel.save()
    return user


@login_required()
def account_view(request, pk):
    if request.method == 'POST':
        data = request.POST
        user = alert_setting(data, pk)
        sender = user.siteusermodel.sender.name
        code = user.siteusermodel.telegram.code
        username = user.username
        email = user.email
        send_instructions.delay(username=username, code=code, email=email, sender=sender)
        return render(request, 'users/succes_sender.html', context={'sender': sender})

    else:
        user = request.user
        shows_user = user.siteusermodel.shows.all()

        return render(request, 'users/cabinet.html', {'shows_user': shows_user})


@login_required()
def ajax_delete_show(request, pk: int) -> JsonResponse:
    if request.is_ajax():
        data = request.GET
        user = User.objects.get(pk=pk)
        show = data['show_pk']
        show = Show.objects.get(pk=int(show))
        user.siteusermodel.shows.remove(show)
        user.siteusermodel.trash.add(show)
        return JsonResponse({'data': 'ok'})


def trash_view(request, pk: int) -> render:
    user = User.objects.get(pk=pk)
    shows = user.siteusermodel.trash.all()
    return render(request, 'users/trash.html', {'shows': shows})


def trash_clear(request, pk: int) -> render:
    user = User.objects.get(pk=pk)
    user.siteusermodel.trash.clear()
    return redirect('users:account', pk=pk)

users/templates/users/cabinet.html
{% load static %}
{% load  filter_status %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/nav.js' %}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'reset.css' %}">
    <link rel="stylesheet" href="{% static 'cabinet.css' %}">

    <title>Личный кабинет</title>
</head>
<body>
    <header class="header">
        <a href="{% url 'index' %}" class="logo-href"><div class="logo">СЛЕДОК <span class="first">T</span><span class="second">V</span> </div></a>
        <div class="float-right">
            
            <a href="{% url 'logout' %}">Выход</a>
            <a href="{% url 'users:trash' pk=user.pk %}"><i class="fa fa-trash fa-2x" aria-hidden="true" id="trash"></i></a>
            <i class="fa fa-check add_clear fa-2x" aria-hidden="true" style="color: red"></i>


        </div>
    </header>
    <div id="description"><p>Моя корзина</p></div>

    <div class="main">
        <div class="first">
        <div class="username">
            <h3>{{ user.username }}</h3>
        </div>



        {% if  user.siteusermodel.send %}


        {% else %}
        <div class="alerts">
            <p>Настройка оповещений</p>
            
            <div class="alert-form">
                <form action='' method="POST">
                    <input type="radio" name="send" id="radio-form" value="telegram" checked>
                    <label for="male">Telgram</label><br>
                    <input type="radio" name="send" id="radio2-form" value="email">
                    <label for="male">Email</label><br>
                    <p class="chois">Выбериите как хотите получать уведомления</p>
                    <input type="checkbox" checked name="time_1" id="" class="time">
                    <label for="time" class="label-time">В день получения информации о выходе новой серии </label><br>
                    {% csrf_token %}
                    <input type="checkbox" checked name="time_2" id="" class="time" >
                    <label for="time"  class="label-time">Напоминание в день выхода новой серии</label><br>
                    <button type="submit" class="send">Отправить</button>
                    

                </form>
            </div>
           

           
        </div>
        {% endif %}
        </div>
        
    <div class="collection" >
        <h3 class="my-text">Моя коллекция</h3>
        <div class="my_shows">
        {% if shows_user %}
        {% for show in shows_user %}
        <div class="show">
         <div class="warnings">{{ show.pk }}</div>
            <img src="{{show.original_image.url}}" alt="" id="img">
            <div class="description">
                <a href="{{ show.get_absolute_url }}">{{ show.rus_fields.name |striptags }}</a>
                <div class="info-eyes">{{ show.status|status }}</div>
                <i class="fas fa-eye eyes"></i>
                <i class="fas fa-trash-alt clear"></i>
                

            </div>
        </div>
        
        {% endfor %}
        {% endif%}
        </div>

    </div>
    </div>

</body>
</html>

users/templates/users/succes_sender.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>оповещение</title>
    <link rel="stylesheet" href="{% static 'succes_sender.css'  %}">
</head>
<body>
    <div class="my-cabinet"><a href="{% url 'users:account' pk=user.pk %}">Вернуться в личный кабинет</a></div>
    <div class="alert">Вы успешно оставили заявку на получение оповещений по {{ sender }} инструкции были направлены на почту<span> {{ user.email }}</span></div>
    
</body>
</html>

users/templates/users/trash.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Корзина</title>
        <link rel="stylesheet" href="{% static 'reset.css' %}">
        <link rel="stylesheet" href="{% static 'trash.css'  %}">
    </head>
    <body>
        <header>
                <div class="header">
                    <p class="my-trash">Моя корзина</p>
                    <p class="clear-trash"><a href="{% url 'users:trash_clear' pk=user.pk %}">Очистить корзину</a></p>
                </div>

        </header>

        <div class="block">
            <div class="all-shows">
                {% for show in shows %}
                    <div class="show">

                        <img src="{{ show.original_image.url }}">
                        <div class="description">{{ show.name }}</div>
                    </div>
                {% endfor %}




            </div>

        </div>

    </body>
</html>